general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita abrir múltiplas instâncias
    before_sleep_cmd = loginctl lock-session    # Bloqueia antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Acende a tela ao acordar
}

# Bloquear após 5 minutos
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Desligar a tela após 10 minutos
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspender após 30 minutos
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
