# Configuração do Hyprlock - Tema Catppuccin Macchiato + Laranja

background {
    monitor =
    path = /home/brizotti/wallpaper/default.jpg
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# HORA
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(252, 123, 83, 1.0) # Laranja Waybar
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 100
    halign = center
    valign = center
}

# DATA
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d de %B")"
    color = rgba(202, 211, 245, 0.8) # Subtext Macchiato
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}

# CAMPO DE SENHA
input-field {
    monitor =
    size = 260, 50
    outline_thickness = 2
    dots_size = 0.28
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(252, 123, 83, 1.0) # Laranja
    inner_color = rgba(36, 39, 58, 0.85)  # Base escura
    font_color = rgba(202, 211, 245, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="##a5adcb"><i>Digite a senha...</i></span>
    hide_input = false
    rounding = 10
    check_color = rgba(238, 212, 159, 1.0) # Amarelo Macchiato
    fail_color = rgba(237, 135, 150, 1.0)  # Vermelho
    fail_text = <i>Senha incorreta! <b>($ATTEMPTS)</b></i>
    position = 0, -80
    halign = center
    valign = center
}
