wallpaper {
    monitor = eDP-1
    path = /home/brizotti/wallpaper/default.jpg
    fit_mode = cover
}

# Fallback para qualquer outro monitor que você conectar
wallpaper {
    monitor = 
    path = /home/brizotti/wallpaper/default.jpg
    fit_mode = cover
}

ipc = on